language: python
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
 - "pypy"

install:
 - "pip install -r requirements.txt --use-mirrors"
 - "pip install ."

script: ./setup.py test

notifications:
  email:
    on_success: always
    on_failure: always
